### ISSUE TITLE
kevinhermann4 - checklist

### ISSUE THREAD

**Issue by kevinhermann4** [githubschool/silver-spoon#5]
No issue yet!
 

- [x] Gain professional training in Git and GitHub
- [x]  Create branches
- [x] Learn Git branching strategies. 
- [x] Create a PR request
- [x] Merge
